server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/open_source_brothers/management_system.git
          username: 695942357@qq.com
          password: qq86502355
          search-paths: /src/main/resources/properties/
      label: master
  application:
    name: config-service